
---

- name: Copy file to C:\
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: C:\
  with_items: 
    - db.sql
    - users.sql
    - script.ps1


- name: create DB
  win_command: sqlcmd -i "C:\db.sql"
  register: sqlcmd_out

- name: print result
  debug:
    var: sqlcmd_out

- name: Update auth option
  win_command: sqlcmd -i "C:\users.sql"
  register: sqlcmd2_out

- name: print result
  debug:
    var: sqlcmd2_out

- name: restart MSSQL
  ansible.windows.win_service:
    name: MSSQLSERVER
    state: restarted


- name: Install an MSSQL-Studio
  win_package:
    path: \\fileserverdb\packages\SSMS-Setup-ENU.exe
    state: present

- name: Install an DOES
  win_package:
    path: \\fileserverdb\packages\DOES.Setup.msi
    state: present

- name: Install  powershell
  win_package:
    path: \\fileserverdb\packages\PowerShell-7.3.6-win-x64.msi
    state: present


- name: Import DOES module and run DOES
  win_command: pwsh C:\script.ps1
  register: output1

- name: print 
  debug:
    var: output1
