- name: check if node exporter exist
  stat:
    path: "{{ mysql_exporter_bin }}"
  register: __check_mysql_exporter_present

- name: create mysql exporter group
  group:
    name: "{{ exporter_group }}"
    state: present

- name: create mysql exporter user
  user:
    name: "{{ exporter_user }}"
    group: "{{ exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create mysql exporter config dir
  file:
    path: "{{ mysql_exporter_dir_conf }}"
    state: directory
    owner: "{{ exporter_user }}"
    group: "{{ exporter_group }}"

- name: if mysql exporter exist get version
  shell: "cat /etc/systemd/system/mysql_exporter.service | grep Version | sed s/'.*Version '//g"
  when: __check_mysql_exporter_present.stat.exists == true
  changed_when: false
  register: __get_mysql_exporter_version
  
- name: download  mysql exporter if not exist
  shell: cd /tmp/; curl -s https://api.github.com/repos/prometheus/mysqld_exporter/releases/latest   | grep browser_download_url   | grep linux-amd64 | cut -d '"' -f 4   | wget -qi -

- name: unzip mysql exporter if not exist
  shell: cd /tmp/; tar xvf mysqld_exporter*.tar.gz


- name: move the binary to the final destination
  copy:
    src: "/tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64/mysqld_exporter"
    dest: "{{ mysql_exporter_bin }}"
    owner: "{{ exporter_user }}"
    group: "{{ exporter_group }}"
    mode: 0755
    remote_src: yes
  when: __check_mysql_exporter_present.stat.exists == false or not __get_mysql_exporter_version.stdout == mysql_exporter_version

- name: clean
  file:
    path: /tmp/mysql_exporter-{{ mysql_exporter_version }}.linux-amd64/
    state: absent




- name: Create user with password and grant priv
  community.mysql.mysql_user:
    state: present
    name: mysqld_exporter
    password: "{{ sqlpass }}"
    login_password: "{{ sqlpass }}"
    priv:
      '*.*' : 'ALL,GRANT'



- name: add mysql exporter config 
  template:
    src: mysqld_exporter.j2
    dest: /etc/.mysqld_exporter.cnf
    owner: root
    group: prometheus
    mode: 0755

- name: install service
  template:
    src: mysql_exporter.service.j2
    dest: /etc/systemd/system/mysql_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_mysql_exporter

- meta: flush_handlers

- name: service always started
  systemd:
    name: mysql_exporter
    state: started
    enabled: yes