yumrepo_server:         "10.21.152.167"
ntp_server: ""
node_exporter_version: "1.5.0"
mysql_exporter_version: "0.15.1"
postgres_exporter_version: "0.12.0"
win_node_exporter_version: "0.20.0"
sql_exporter_version: "0.5"
node_exporter_bin: /usr/local/bin/node_exporter
mysql_exporter_bin: /usr/local/bin/mysqld_exporter
postgres_exporter_bin: /usr/local/bin/
exporter_user: prometheus
exporter_group: "prometheus"
node_exporter_dir_conf: /etc/node_exporter
mysql_exporter_dir_conf: /etc/mysql_exporter
postgres_exporter_dir_conf: /etc/postgres_exporter
sqlpass: "Osmium76"
postgrespass: ""
postgres_db_name: postgresdbapp
postgresdb_user: dbuser
oracle_pdb: pdb1
oracle_sid: cdb1
oracle_home: /u01/app/oracle/product/19.0.0/dbhome_1
oracle_base: /u01/app/oracle
oracle_inventory: /u01/app/oraInventory
stage_dir: /u01/stage
oradbsoft_rsp: oracle-instal
ips:
  - 10.21.210.9
  - 10.21.210.11
nfs_share: 10.21.220.76:/saphana
