---
    # common playbook
  - hosts: 'localhost'
    gather_facts: false
    # vars_files:
    #   - "hosts.yml"
    roles:
      - {role: prometheus-config}

  - hosts: all
    become:        yes
    become_method: sudo
    gather_facts:  yes
    roles:
    - {role: prometheus-update}

      
